/*
: Copyright (c) 2012-2018 Dan Grossman. All rights reserved.
 @license: Licensed under the MIT license. See http://www.opensource.org/licenses/mit-license.php
 @website: http://www.daterangepicker.com/
*/
var $jscomp={scope:{},findInternal:function(e,f,k){e instanceof String&&(e=String(e));for(var b=e.length,a=0;a<b;a++){var c=e[a];if(f.call(k,c,a,e))return{i:a,v:c}}return{i:-1,v:void 0}}};$jscomp.defineProperty="function"==typeof Object.defineProperties?Object.defineProperty:function(e,f,k){if(k.get||k.set)throw new TypeError("ES3 does not support getters and setters.");e!=Array.prototype&&e!=Object.prototype&&(e[f]=k.value)};
$jscomp.getGlobal=function(e){return"undefined"!=typeof window&&window===e?e:"undefined"!=typeof global&&null!=global?global:e};$jscomp.global=$jscomp.getGlobal(this);$jscomp.polyfill=function(e,f,k,b){if(f){k=$jscomp.global;e=e.split(".");for(b=0;b<e.length-1;b++){var a=e[b];a in k||(k[a]={});k=k[a]}e=e[e.length-1];b=k[e];f=f(b);f!=b&&null!=f&&$jscomp.defineProperty(k,e,{configurable:!0,writable:!0,value:f})}};
$jscomp.polyfill("Array.prototype.find",function(e){return e?e:function(e,k){return $jscomp.findInternal(this,e,k).v}},"es6-impl","es3");
(function(e,f){if("function"===typeof define&&define.amd)define(["moment","jquery"],function(a,b){b.fn||(b.fn={});return f(a,b)});else if("object"===typeof module&&module.exports){var k="undefined"!=typeof window?window.jQuery:void 0;k||(k=require("jquery"),k.fn||(k.fn={}));var b="undefined"!=typeof window&&"undefined"!=typeof window.moment?window.moment:require("moment");module.exports=f(b,k)}else e.daterangepicker=f(e.moment,e.jQuery)})(this,function(e,f){var k=function(b,a,c){this.parentEl="body";
this.element=f(b);this.startDate=e().startOf("day");this.endDate=e().endOf("day");this.showDropdowns=this.singleDatePicker=this.autoApply=this.maxSpan=this.maxDate=this.minDate=!1;this.minYear=e().subtract(100,"year").format("YYYY");this.maxYear=e().add(100,"year").format("YYYY");this.showISOWeekNumbers=this.showWeekNumbers=!1;this.showCustomRangeLabel=!0;this.timePicker24Hour=this.timePicker=!1;this.timePickerIncrement=1;this.timePickerSeconds=!1;this.autoUpdateInput=this.linkedCalendars=!0;this.alwaysShowCalendars=
!1;this.ranges={};this.opens="right";this.element.hasClass("pull-right")&&(this.opens="left");this.drops="down";this.element.hasClass("dropup")&&(this.drops="up");this.buttonClasses="btn btn-sm";this.applyButtonClasses="btn-primary";this.cancelButtonClasses="btn-default";this.locale={direction:"ltr",format:e.localeData().longDateFormat("L"),separator:" - ",applyLabel:"Apply",cancelLabel:"Cancel",weekLabel:"W",customRangeLabel:"Custom Range",daysOfWeek:e.weekdaysMin(),monthNames:e.monthsShort(),firstDay:e.localeData().firstDayOfWeek()};
this.callback=function(){};this.isShowing=!1;this.leftCalendar={};this.rightCalendar={};if("object"!==typeof a||null===a)a={};a=f.extend(this.element.data(),a);"string"===typeof a.template||a.template instanceof f||(a.template='<div class="daterangepicker"><div class="ranges"></div><div class="drp-calendar left"><div class="calendar-table"></div><div class="calendar-time"></div></div><div class="drp-calendar right"><div class="calendar-table"></div><div class="calendar-time"></div></div><div class="drp-buttons"><span class="drp-selected"></span><button class="cancelBtn" type="button"></button><button class="applyBtn" disabled="disabled" type="button"></button> </div></div>');
this.parentEl=a.parentEl&&f(a.parentEl).length?f(a.parentEl):f(this.parentEl);this.container=f(a.template).appendTo(this.parentEl);if("object"===typeof a.locale&&("string"===typeof a.locale.direction&&(this.locale.direction=a.locale.direction),"string"===typeof a.locale.format&&(this.locale.format=a.locale.format),"string"===typeof a.locale.separator&&(this.locale.separator=a.locale.separator),"object"===typeof a.locale.daysOfWeek&&(this.locale.daysOfWeek=a.locale.daysOfWeek.slice()),"object"===typeof a.locale.monthNames&&
(this.locale.monthNames=a.locale.monthNames.slice()),"number"===typeof a.locale.firstDay&&(this.locale.firstDay=a.locale.firstDay),"string"===typeof a.locale.applyLabel&&(this.locale.applyLabel=a.locale.applyLabel),"string"===typeof a.locale.cancelLabel&&(this.locale.cancelLabel=a.locale.cancelLabel),"string"===typeof a.locale.weekLabel&&(this.locale.weekLabel=a.locale.weekLabel),"string"===typeof a.locale.customRangeLabel)){var d=document.createElement("textarea");d.innerHTML=a.locale.customRangeLabel;
d=d.value;this.locale.customRangeLabel=d}this.container.addClass(this.locale.direction);"string"===typeof a.startDate&&(this.startDate=e(a.startDate,this.locale.format));"string"===typeof a.endDate&&(this.endDate=e(a.endDate,this.locale.format));"string"===typeof a.minDate&&(this.minDate=e(a.minDate,this.locale.format));"string"===typeof a.maxDate&&(this.maxDate=e(a.maxDate,this.locale.format));"object"===typeof a.startDate&&(this.startDate=e(a.startDate));"object"===typeof a.endDate&&(this.endDate=
e(a.endDate));"object"===typeof a.minDate&&(this.minDate=e(a.minDate));"object"===typeof a.maxDate&&(this.maxDate=e(a.maxDate));this.minDate&&this.startDate.isBefore(this.minDate)&&(this.startDate=this.minDate.clone());this.maxDate&&this.endDate.isAfter(this.maxDate)&&(this.endDate=this.maxDate.clone());"string"===typeof a.applyButtonClasses&&(this.applyButtonClasses=a.applyButtonClasses);"string"===typeof a.applyClass&&(this.applyButtonClasses=a.applyClass);"string"===typeof a.cancelButtonClasses&&
(this.cancelButtonClasses=a.cancelButtonClasses);"string"===typeof a.cancelClass&&(this.cancelButtonClasses=a.cancelClass);"object"===typeof a.maxSpan&&(this.maxSpan=a.maxSpan);"object"===typeof a.dateLimit&&(this.maxSpan=a.dateLimit);"string"===typeof a.opens&&(this.opens=a.opens);"string"===typeof a.drops&&(this.drops=a.drops);"boolean"===typeof a.showWeekNumbers&&(this.showWeekNumbers=a.showWeekNumbers);"boolean"===typeof a.showISOWeekNumbers&&(this.showISOWeekNumbers=a.showISOWeekNumbers);"string"===
typeof a.buttonClasses&&(this.buttonClasses=a.buttonClasses);"object"===typeof a.buttonClasses&&(this.buttonClasses=a.buttonClasses.join(" "));"boolean"===typeof a.showDropdowns&&(this.showDropdowns=a.showDropdowns);"number"===typeof a.minYear&&(this.minYear=a.minYear);"number"===typeof a.maxYear&&(this.maxYear=a.maxYear);"boolean"===typeof a.showCustomRangeLabel&&(this.showCustomRangeLabel=a.showCustomRangeLabel);"boolean"===typeof a.singleDatePicker&&(this.singleDatePicker=a.singleDatePicker)&&
(this.endDate=this.startDate.clone());"boolean"===typeof a.timePicker&&(this.timePicker=a.timePicker);"boolean"===typeof a.timePickerSeconds&&(this.timePickerSeconds=a.timePickerSeconds);"number"===typeof a.timePickerIncrement&&(this.timePickerIncrement=a.timePickerIncrement);"boolean"===typeof a.timePicker24Hour&&(this.timePicker24Hour=a.timePicker24Hour);"boolean"===typeof a.autoApply&&(this.autoApply=a.autoApply);"boolean"===typeof a.autoUpdateInput&&(this.autoUpdateInput=a.autoUpdateInput);"boolean"===
typeof a.linkedCalendars&&(this.linkedCalendars=a.linkedCalendars);"function"===typeof a.isInvalidDate&&(this.isInvalidDate=a.isInvalidDate);"function"===typeof a.isCustomDate&&(this.isCustomDate=a.isCustomDate);"boolean"===typeof a.alwaysShowCalendars&&(this.alwaysShowCalendars=a.alwaysShowCalendars);if(0!=this.locale.firstDay)for(b=this.locale.firstDay;0<b;)this.locale.daysOfWeek.push(this.locale.daysOfWeek.shift()),b--;var p,h;if("undefined"===typeof a.startDate&&"undefined"===typeof a.endDate&&
f(this.element).is(":text")){var d=f(this.element).val(),g=d.split(this.locale.separator);b=p=null;2==g.length?(b=e(g[0],this.locale.format),p=e(g[1],this.locale.format)):this.singleDatePicker&&""!==d&&(b=e(d,this.locale.format),p=e(d,this.locale.format));null!==b&&null!==p&&(this.setStartDate(b),this.setEndDate(p))}if("object"===typeof a.ranges){for(h in a.ranges)b="string"===typeof a.ranges[h][0]?e(a.ranges[h][0],this.locale.format):e(a.ranges[h][0]),p="string"===typeof a.ranges[h][1]?e(a.ranges[h][1],
this.locale.format):e(a.ranges[h][1]),this.minDate&&b.isBefore(this.minDate)&&(b=this.minDate.clone()),d=this.maxDate,this.maxSpan&&d&&b.clone().add(this.maxSpan).isAfter(d)&&(d=b.clone().add(this.maxSpan)),d&&p.isAfter(d)&&(p=d.clone()),this.minDate&&p.isBefore(this.minDate,this.timepicker?"minute":"day")||d&&b.isAfter(d,this.timepicker?"minute":"day")||(d=document.createElement("textarea"),d.innerHTML=h,d=d.value,this.ranges[d]=[b,p]);b="<ul>";for(h in this.ranges)b+='<li data-range-key="'+h+'">'+
h+"</li>";this.showCustomRangeLabel&&(b+='<li data-range-key="'+this.locale.customRangeLabel+'">'+this.locale.customRangeLabel+"</li>");b+="</ul>";this.container.find(".ranges").prepend(b)}"function"===typeof c&&(this.callback=c);this.timePicker||(this.startDate=this.startDate.startOf("day"),this.endDate=this.endDate.endOf("day"),this.container.find(".calendar-time").hide());this.timePicker&&this.autoApply&&(this.autoApply=!1);this.autoApply&&this.container.addClass("auto-apply");"object"===typeof a.ranges&&
this.container.addClass("show-ranges");this.singleDatePicker&&(this.container.addClass("single"),this.container.find(".drp-calendar.left").addClass("single"),this.container.find(".drp-calendar.left").show(),this.container.find(".drp-calendar.right").hide(),this.timePicker||this.container.addClass("auto-apply"));("undefined"===typeof a.ranges&&!this.singleDatePicker||this.alwaysShowCalendars)&&this.container.addClass("show-calendar");this.container.addClass("opens"+this.opens);this.container.find(".applyBtn, .cancelBtn").addClass(this.buttonClasses);
this.applyButtonClasses.length&&this.container.find(".applyBtn").addClass(this.applyButtonClasses);this.cancelButtonClasses.length&&this.container.find(".cancelBtn").addClass(this.cancelButtonClasses);this.container.find(".applyBtn").html(this.locale.applyLabel);this.container.find(".cancelBtn").html(this.locale.cancelLabel);this.container.find(".drp-calendar").on("click.daterangepicker",".prev",f.proxy(this.clickPrev,this)).on("click.daterangepicker",".next",f.proxy(this.clickNext,this)).on("mousedown.daterangepicker",
"td.available",f.proxy(this.clickDate,this)).on("mouseenter.daterangepicker","td.available",f.proxy(this.hoverDate,this)).on("change.daterangepicker","select.yearselect",f.proxy(this.monthOrYearChanged,this)).on("change.daterangepicker","select.monthselect",f.proxy(this.monthOrYearChanged,this)).on("change.daterangepicker","select.hourselect,select.minuteselect,select.secondselect,select.ampmselect",f.proxy(this.timeChanged,this));this.container.find(".ranges").on("click.daterangepicker","li",f.proxy(this.clickRange,
this));this.container.find(".drp-buttons").on("click.daterangepicker","button.applyBtn",f.proxy(this.clickApply,this)).on("click.daterangepicker","button.cancelBtn",f.proxy(this.clickCancel,this));if(this.element.is("input")||this.element.is("button"))this.element.on({"click.daterangepicker":f.proxy(this.show,this),"focus.daterangepicker":f.proxy(this.show,this),"keyup.daterangepicker":f.proxy(this.elementChanged,this),"keydown.daterangepicker":f.proxy(this.keydown,this)});else this.element.on("click.daterangepicker",
f.proxy(this.toggle,this)),this.element.on("keydown.daterangepicker",f.proxy(this.toggle,this));this.updateElement()};k.prototype={constructor:k,setStartDate:function(b){"string"===typeof b&&(this.startDate=e(b,this.locale.format));"object"===typeof b&&(this.startDate=e(b));this.timePicker||(this.startDate=this.startDate.startOf("day"));this.timePicker&&this.timePickerIncrement&&this.startDate.minute(Math.round(this.startDate.minute()/this.timePickerIncrement)*this.timePickerIncrement);this.minDate&&
this.startDate.isBefore(this.minDate)&&(this.startDate=this.minDate.clone(),this.timePicker&&this.timePickerIncrement&&this.startDate.minute(Math.round(this.startDate.minute()/this.timePickerIncrement)*this.timePickerIncrement));this.maxDate&&this.startDate.isAfter(this.maxDate)&&(this.startDate=this.maxDate.clone(),this.timePicker&&this.timePickerIncrement&&this.startDate.minute(Math.floor(this.startDate.minute()/this.timePickerIncrement)*this.timePickerIncrement));this.isShowing||this.updateElement();
this.updateMonthsInView()},setEndDate:function(b){"string"===typeof b&&(this.endDate=e(b,this.locale.format));"object"===typeof b&&(this.endDate=e(b));this.timePicker||(this.endDate=this.endDate.add(1,"d").startOf("day").subtract(1,"second"));this.timePicker&&this.timePickerIncrement&&this.endDate.minute(Math.round(this.endDate.minute()/this.timePickerIncrement)*this.timePickerIncrement);this.endDate.isBefore(this.startDate)&&(this.endDate=this.startDate.clone());this.maxDate&&this.endDate.isAfter(this.maxDate)&&
(this.endDate=this.maxDate.clone());this.maxSpan&&this.startDate.clone().add(this.maxSpan).isBefore(this.endDate)&&(this.endDate=this.startDate.clone().add(this.maxSpan));this.previousRightTime=this.endDate.clone();this.container.find(".drp-selected").html(this.startDate.format(this.locale.format)+this.locale.separator+this.endDate.format(this.locale.format));this.isShowing||this.updateElement();this.updateMonthsInView()},isInvalidDate:function(){return!1},isCustomDate:function(){return!1},updateView:function(){this.timePicker&&
(this.renderTimePicker("left"),this.renderTimePicker("right"),this.endDate?this.container.find(".right .calendar-time select").removeAttr("disabled").removeClass("disabled"):this.container.find(".right .calendar-time select").attr("disabled","disabled").addClass("disabled"));this.endDate&&this.container.find(".drp-selected").html(this.startDate.format(this.locale.format)+this.locale.separator+this.endDate.format(this.locale.format));this.updateMonthsInView();this.updateCalendars();this.updateFormInputs()},
updateMonthsInView:function(){if(this.endDate){if(!this.singleDatePicker&&this.leftCalendar.month&&this.rightCalendar.month&&(this.startDate.format("YYYY-MM")==this.leftCalendar.month.format("YYYY-MM")||this.startDate.format("YYYY-MM")==this.rightCalendar.month.format("YYYY-MM"))&&(this.endDate.format("YYYY-MM")==this.leftCalendar.month.format("YYYY-MM")||this.endDate.format("YYYY-MM")==this.rightCalendar.month.format("YYYY-MM")))return;this.leftCalendar.month=this.startDate.clone().date(2);this.linkedCalendars||
this.endDate.month()==this.startDate.month()&&this.endDate.year()==this.startDate.year()?this.rightCalendar.month=this.startDate.clone().date(2).add(1,"month"):this.rightCalendar.month=this.endDate.clone().date(2)}else this.leftCalendar.month.format("YYYY-MM")!=this.startDate.format("YYYY-MM")&&this.rightCalendar.month.format("YYYY-MM")!=this.startDate.format("YYYY-MM")&&(this.leftCalendar.month=this.startDate.clone().date(2),this.rightCalendar.month=this.startDate.clone().date(2).add(1,"month"));
this.maxDate&&this.linkedCalendars&&!this.singleDatePicker&&this.rightCalendar.month>this.maxDate&&(this.rightCalendar.month=this.maxDate.clone().date(2),this.leftCalendar.month=this.maxDate.clone().date(2).subtract(1,"month"))},updateCalendars:function(){if(this.timePicker){var b,a,c;if(this.endDate){if(b=parseInt(this.container.find(".left .hourselect").val(),10),a=parseInt(this.container.find(".left .minuteselect").val(),10),c=this.timePickerSeconds?parseInt(this.container.find(".left .secondselect").val(),
10):0,!this.timePicker24Hour){var d=this.container.find(".left .ampmselect").val();"PM"===d&&12>b&&(b+=12);"AM"===d&&12===b&&(b=0)}}else b=parseInt(this.container.find(".right .hourselect").val(),10),a=parseInt(this.container.find(".right .minuteselect").val(),10),c=this.timePickerSeconds?parseInt(this.container.find(".right .secondselect").val(),10):0,this.timePicker24Hour||(d=this.container.find(".right .ampmselect").val(),"PM"===d&&12>b&&(b+=12),"AM"===d&&12===b&&(b=0));this.leftCalendar.month.hour(b).minute(a).second(c);
this.rightCalendar.month.hour(b).minute(a).second(c)}this.renderCalendar("left");this.renderCalendar("right");this.container.find(".ranges li").removeClass("active");null!=this.endDate&&this.calculateChosenLabel()},renderCalendar:function(b){var a="left"==b?this.leftCalendar:this.rightCalendar,c=a.month.month(),d=a.month.year(),p=a.month.hour(),h=a.month.minute(),g=a.month.second(),a=e([d,c]).daysInMonth(),l=e([d,c,1]),k=e([d,c,a]),c=e(l).subtract(1,"month").month(),d=e(l).subtract(1,"month").year(),
m=e([d,c]).daysInMonth(),r=l.day(),a=[];a.firstDay=l;a.lastDay=k;for(l=0;6>l;l++)a[l]=[];l=m-r+this.locale.firstDay+1;l>m&&(l-=7);r==this.locale.firstDay&&(l=m-6);m=e([d,c,l,12,h,g]);for(d=c=l=0;42>l;l++,c++,m=e(m).add(24,"hour"))0<l&&0===c%7&&(c=0,d++),a[d][c]=m.clone().hour(p).minute(h).second(g),m.hour(12),this.minDate&&a[d][c].format("YYYY-MM-DD")==this.minDate.format("YYYY-MM-DD")&&a[d][c].isBefore(this.minDate)&&"left"==b&&(a[d][c]=this.minDate.clone()),this.maxDate&&a[d][c].format("YYYY-MM-DD")==
this.maxDate.format("YYYY-MM-DD")&&a[d][c].isAfter(this.maxDate)&&"right"==b&&(a[d][c]=this.maxDate.clone());"left"==b?this.leftCalendar.calendar=a:this.rightCalendar.calendar=a;var c="left"==b?this.minDate:this.startDate,p=this.maxDate,n='<table class="table-condensed">',n=n+"<thead>",n=n+"<tr>";if(this.showWeekNumbers||this.showISOWeekNumbers)n+="<th></th>";n=c&&!c.isBefore(a.firstDay)||this.linkedCalendars&&"left"!=b?n+"<th></th>":n+'<th class="prev available"><span></span></th>';h=this.locale.monthNames[a[1][1].month()]+
a[1][1].format(" YYYY");if(this.showDropdowns){for(var m=a[1][1].month(),h=a[1][1].year(),g=p&&p.year()||this.maxYear,d=c&&c.year()||this.minYear,r=h==d,k=h==g,l='<select class="monthselect">',q=0;12>q;q++)l=(!r||q>=c.month())&&(!k||q<=p.month())?l+("<option value='"+q+"'"+(q===m?" selected='selected'":"")+">"+this.locale.monthNames[q]+"</option>"):l+("<option value='"+q+"'"+(q===m?" selected='selected'":"")+" disabled='disabled'>"+this.locale.monthNames[q]+"</option>");for(c='<select class="yearselect">';d<=
g;d++)c+='<option value="'+d+'"'+(d===h?' selected="selected"':"")+">"+d+"</option>";h=l+"</select>"+(c+"</select>")}n+='<th colspan="5" class="month">'+h+"</th>";n=p&&!p.isAfter(a.lastDay)||this.linkedCalendars&&"right"!=b&&!this.singleDatePicker?n+"<th></th>":n+'<th class="next available"><span></span></th>';n+="</tr>";n+="<tr>";if(this.showWeekNumbers||this.showISOWeekNumbers)n+='<th class="week">'+this.locale.weekLabel+"</th>";f.each(this.locale.daysOfWeek,function(a,b){n+="<th>"+b+"</th>"});
n+="</tr>";n+="</thead>";n+="<tbody>";null==this.endDate&&this.maxSpan&&(h=this.startDate.clone().add(this.maxSpan).endOf("day"),!p||h.isBefore(p))&&(p=h);for(d=0;6>d;d++){n+="<tr>";this.showWeekNumbers?n+='<td class="week">'+a[d][0].week()+"</td>":this.showISOWeekNumbers&&(n+='<td class="week">'+a[d][0].isoWeek()+"</td>");for(c=0;7>c;c++){h=[];a[d][c].isSame(new Date,"day")&&h.push("today");5<a[d][c].isoWeekday()&&h.push("weekend");a[d][c].month()!=a[1][1].month()&&h.push("off");this.minDate&&a[d][c].isBefore(this.minDate,
"day")&&h.push("off","disabled");p&&a[d][c].isAfter(p,"day")&&h.push("off","disabled");this.isInvalidDate(a[d][c])&&h.push("off","disabled");a[d][c].format("YYYY-MM-DD")==this.startDate.format("YYYY-MM-DD")&&h.push("active","start-date");null!=this.endDate&&a[d][c].format("YYYY-MM-DD")==this.endDate.format("YYYY-MM-DD")&&h.push("active","end-date");null!=this.endDate&&a[d][c]>this.startDate&&a[d][c]<this.endDate&&h.push("in-range");g=this.isCustomDate(a[d][c]);!1!==g&&("string"===typeof g?h.push(g):
Array.prototype.push.apply(h,g));g="";m=!1;for(l=0;l<h.length;l++)g+=h[l]+" ","disabled"==h[l]&&(m=!0);m||(g+="available");n+='<td class="'+g.replace(/^\s+|\s+$/g,"")+'" data-title="r'+d+"c"+c+'">'+a[d][c].date()+"</td>"}n+="</tr>"}n+="</tbody>";n+="</table>";this.container.find(".drp-calendar."+b+" .calendar-table").html(n)},renderTimePicker:function(b){if("right"!=b||this.endDate){var a,c,d,e=this.maxDate;!this.maxSpan||this.maxDate&&!this.startDate.clone().add(this.maxSpan).isAfter(this.maxDate)||
(e=this.startDate.clone().add(this.maxSpan));"left"==b?(c=this.startDate.clone(),d=this.minDate):"right"==b&&(c=this.endDate.clone(),d=this.startDate,a=this.container.find(".drp-calendar.right .calendar-time"),""!=a.html()&&(c.hour(c.hour()||a.find(".hourselect option:selected").val()),c.minute(c.minute()||a.find(".minuteselect option:selected").val()),c.second(c.second()||a.find(".secondselect option:selected").val()),this.timePicker24Hour||(a=a.find(".ampmselect option:selected").val(),"PM"===a&&
12>c.hour()&&c.hour(c.hour()+12),"AM"===a&&12===c.hour()&&c.hour(0))),c.isBefore(this.startDate)&&(c=this.startDate.clone()),e&&c.isAfter(e)&&(c=e.clone()));a='<select class="hourselect">';for(var f=this.timePicker24Hour?23:12,g=this.timePicker24Hour?0:1;g<=f;g++){var l=g;this.timePicker24Hour||(l=12<=c.hour()?12==g?12:g+12:12==g?0:g);var k=c.clone().hour(l),m=!1;d&&k.minute(59).isBefore(d)&&(m=!0);e&&k.minute(0).isAfter(e)&&(m=!0);a=l!=c.hour()||m?m?a+('<option value="'+g+'" disabled="disabled" class="disabled">'+
g+"</option>"):a+('<option value="'+g+'">'+g+"</option>"):a+('<option value="'+g+'" selected="selected">'+g+"</option>")}a+='</select> : <select class="minuteselect">';for(g=0;60>g;g+=this.timePickerIncrement)f=10>g?"0"+g:g,k=c.clone().minute(g),m=!1,d&&k.second(59).isBefore(d)&&(m=!0),e&&k.second(0).isAfter(e)&&(m=!0),a=c.minute()!=g||m?m?a+('<option value="'+g+'" disabled="disabled" class="disabled">'+f+"</option>"):a+('<option value="'+g+'">'+f+"</option>"):a+('<option value="'+g+'" selected="selected">'+
f+"</option>");a+="</select> ";if(this.timePickerSeconds){a+=': <select class="secondselect">';for(g=0;60>g;g++)f=10>g?"0"+g:g,k=c.clone().second(g),m=!1,d&&k.isBefore(d)&&(m=!0),e&&k.isAfter(e)&&(m=!0),a=c.second()!=g||m?m?a+('<option value="'+g+'" disabled="disabled" class="disabled">'+f+"</option>"):a+('<option value="'+g+'">'+f+"</option>"):a+('<option value="'+g+'" selected="selected">'+f+"</option>");a+="</select> "}this.timePicker24Hour||(a+='<select class="ampmselect">',k=g="",d&&c.clone().hour(12).minute(0).second(0).isBefore(d)&&
(g=' disabled="disabled" class="disabled"'),e&&c.clone().hour(0).minute(0).second(0).isAfter(e)&&(k=' disabled="disabled" class="disabled"'),a=12<=c.hour()?a+('<option value="AM"'+g+'>AM</option><option value="PM" selected="selected"'+k+">PM</option>"):a+('<option value="AM" selected="selected"'+g+'>AM</option><option value="PM"'+k+">PM</option>"),a+="</select>");this.container.find(".drp-calendar."+b+" .calendar-time").html(a)}},updateFormInputs:function(){this.singleDatePicker||this.endDate&&(this.startDate.isBefore(this.endDate)||
this.startDate.isSame(this.endDate))?this.container.find("button.applyBtn").removeAttr("disabled"):this.container.find("button.applyBtn").attr("disabled","disabled")},move:function(){var b=0,a=0,c=f(window).width();this.parentEl.is("body")||(b=this.parentEl.offset().top-this.parentEl.scrollTop(),a=this.parentEl.offset().left-this.parentEl.scrollLeft(),c=this.parentEl[0].clientWidth+this.parentEl.offset().left);b="up"==this.drops?this.element.offset().top-this.container.outerHeight()-b:this.element.offset().top+
this.element.outerHeight()-b;this.container["up"==this.drops?"addClass":"removeClass"]("drop-up");"left"==this.opens?(this.container.css({top:b,right:c-this.element.offset().left-this.element.outerWidth(),left:"auto"}),0>this.container.offset().left&&this.container.css({right:"auto",left:9})):"center"==this.opens?(this.container.css({top:b,left:this.element.offset().left-a+this.element.outerWidth()/2-this.container.outerWidth()/2,right:"auto"}),0>this.container.offset().left&&this.container.css({right:"auto",
left:9})):(this.container.css({top:b,left:this.element.offset().left-a,right:"auto"}),this.container.offset().left+this.container.outerWidth()>f(window).width()&&this.container.css({left:"auto",right:0}))},show:function(b){this.isShowing||(this._outsideClickProxy=f.proxy(function(a){this.outsideClick(a)},this),f(document).on("mousedown.daterangepicker",this._outsideClickProxy).on("touchend.daterangepicker",this._outsideClickProxy).on("click.daterangepicker","[data-toggle=dropdown]",this._outsideClickProxy).on("focusin.daterangepicker",
this._outsideClickProxy),f(window).on("resize.daterangepicker",f.proxy(function(a){this.move(a)},this)),this.oldStartDate=this.startDate.clone(),this.oldEndDate=this.endDate.clone(),this.previousRightTime=this.endDate.clone(),this.updateView(),this.container.show(),this.move(),this.element.trigger("show.daterangepicker",this),this.isShowing=!0)},hide:function(b){this.isShowing&&(this.endDate||(this.startDate=this.oldStartDate.clone(),this.endDate=this.oldEndDate.clone()),this.startDate.isSame(this.oldStartDate)&&
this.endDate.isSame(this.oldEndDate)||this.callback(this.startDate.clone(),this.endDate.clone(),this.chosenLabel),this.updateElement(),f(document).off(".daterangepicker"),f(window).off(".daterangepicker"),this.container.hide(),this.element.trigger("hide.daterangepicker",this),this.isShowing=!1)},toggle:function(b){this.isShowing?this.hide():this.show()},outsideClick:function(b){var a=f(b.target);"focusin"==b.type||a.closest(this.element).length||a.closest(this.container).length||a.closest(".calendar-table").length||
(this.hide(),this.element.trigger("outsideClick.daterangepicker",this))},showCalendars:function(){this.container.addClass("show-calendar");this.move();this.element.trigger("showCalendar.daterangepicker",this)},hideCalendars:function(){this.container.removeClass("show-calendar");this.element.trigger("hideCalendar.daterangepicker",this)},clickRange:function(b){this.chosenLabel=b=b.target.getAttribute("data-range-key");b==this.locale.customRangeLabel?this.showCalendars():(b=this.ranges[b],this.startDate=
b[0],this.endDate=b[1],this.timePicker||(this.startDate.startOf("day"),this.endDate.endOf("day")),this.alwaysShowCalendars||this.hideCalendars(),this.clickApply())},clickPrev:function(b){f(b.target).parents(".drp-calendar").hasClass("left")?(this.leftCalendar.month.subtract(1,"month"),this.linkedCalendars&&this.rightCalendar.month.subtract(1,"month")):this.rightCalendar.month.subtract(1,"month");this.updateCalendars()},clickNext:function(b){f(b.target).parents(".drp-calendar").hasClass("left")?this.leftCalendar.month.add(1,
"month"):(this.rightCalendar.month.add(1,"month"),this.linkedCalendars&&this.leftCalendar.month.add(1,"month"));this.updateCalendars()},hoverDate:function(b){if(f(b.target).hasClass("available")){var a=f(b.target).attr("data-title"),c=a.substr(1,1),a=a.substr(3,1),d=f(b.target).parents(".drp-calendar").hasClass("left")?this.leftCalendar.calendar[c][a]:this.rightCalendar.calendar[c][a],e=this.leftCalendar,k=this.rightCalendar,g=this.startDate;this.endDate||this.container.find(".drp-calendar tbody td").each(function(a,
b){if(!f(b).hasClass("week")){var c=f(b).attr("data-title"),h=c.substr(1,1),c=c.substr(3,1),h=f(b).parents(".drp-calendar").hasClass("left")?e.calendar[h][c]:k.calendar[h][c];h.isAfter(g)&&h.isBefore(d)||h.isSame(d,"day")?f(b).addClass("in-range"):f(b).removeClass("in-range")}})}},clickDate:function(b){if(f(b.target).hasClass("available")){var a=f(b.target).attr("data-title"),c=a.substr(1,1),a=a.substr(3,1),c=f(b.target).parents(".drp-calendar").hasClass("left")?this.leftCalendar.calendar[c][a]:this.rightCalendar.calendar[c][a];
if(this.endDate||c.isBefore(this.startDate,"day")){if(this.timePicker){a=parseInt(this.container.find(".left .hourselect").val(),10);if(!this.timePicker24Hour){var d=this.container.find(".left .ampmselect").val();"PM"===d&&12>a&&(a+=12);"AM"===d&&12===a&&(a=0)}var d=parseInt(this.container.find(".left .minuteselect").val(),10),e=this.timePickerSeconds?parseInt(this.container.find(".left .secondselect").val(),10):0,c=c.clone().hour(a).minute(d).second(e)}this.endDate=null;this.setStartDate(c.clone())}else!this.endDate&&
c.isBefore(this.startDate)?this.setEndDate(this.startDate.clone()):(this.timePicker&&(a=parseInt(this.container.find(".right .hourselect").val(),10),this.timePicker24Hour||(d=this.container.find(".right .ampmselect").val(),"PM"===d&&12>a&&(a+=12),"AM"===d&&12===a&&(a=0)),d=parseInt(this.container.find(".right .minuteselect").val(),10),e=this.timePickerSeconds?parseInt(this.container.find(".right .secondselect").val(),10):0,c=c.clone().hour(a).minute(d).second(e)),this.setEndDate(c.clone()),this.autoApply&&
(this.calculateChosenLabel(),this.clickApply()));this.singleDatePicker&&(this.setEndDate(this.startDate),this.timePicker||this.clickApply());this.updateView();b.stopPropagation()}},calculateChosenLabel:function(){var b=!0,a=0,c;for(c in this.ranges){if(this.timePicker){var d=this.timePickerSeconds?"YYYY-MM-DD hh:mm:ss":"YYYY-MM-DD hh:mm";if(this.startDate.format(d)==this.ranges[c][0].format(d)&&this.endDate.format(d)==this.ranges[c][1].format(d)){b=!1;this.chosenLabel=this.container.find(".ranges li:eq("+
a+")").addClass("active").attr("data-range-key");break}}else if(this.startDate.format("YYYY-MM-DD")==this.ranges[c][0].format("YYYY-MM-DD")&&this.endDate.format("YYYY-MM-DD")==this.ranges[c][1].format("YYYY-MM-DD")){b=!1;this.chosenLabel=this.container.find(".ranges li:eq("+a+")").addClass("active").attr("data-range-key");break}a++}b&&(this.chosenLabel=this.showCustomRangeLabel?this.container.find(".ranges li:last").addClass("active").attr("data-range-key"):null,this.showCalendars())},clickApply:function(b){this.hide();
this.element.trigger("apply.daterangepicker",this)},clickCancel:function(b){this.startDate=this.oldStartDate;this.endDate=this.oldEndDate;this.hide();this.element.trigger("cancel.daterangepicker",this)},monthOrYearChanged:function(b){b=f(b.target).closest(".drp-calendar").hasClass("left");var a=this.container.find(".drp-calendar."+(b?"left":"right")),c=parseInt(a.find(".monthselect").val(),10),a=a.find(".yearselect").val();!b&&(a<this.startDate.year()||a==this.startDate.year()&&c<this.startDate.month())&&
(c=this.startDate.month(),a=this.startDate.year());this.minDate&&(a<this.minDate.year()||a==this.minDate.year()&&c<this.minDate.month())&&(c=this.minDate.month(),a=this.minDate.year());this.maxDate&&(a>this.maxDate.year()||a==this.maxDate.year()&&c>this.maxDate.month())&&(c=this.maxDate.month(),a=this.maxDate.year());b?(this.leftCalendar.month.month(c).year(a),this.linkedCalendars&&(this.rightCalendar.month=this.leftCalendar.month.clone().add(1,"month"))):(this.rightCalendar.month.month(c).year(a),
this.linkedCalendars&&(this.leftCalendar.month=this.rightCalendar.month.clone().subtract(1,"month")));this.updateCalendars()},timeChanged:function(b){var a=f(b.target).closest(".drp-calendar"),c=a.hasClass("left");b=parseInt(a.find(".hourselect").val(),10);var d=parseInt(a.find(".minuteselect").val(),10),e=this.timePickerSeconds?parseInt(a.find(".secondselect").val(),10):0;this.timePicker24Hour||(a=a.find(".ampmselect").val(),"PM"===a&&12>b&&(b+=12),"AM"===a&&12===b&&(b=0));c?(c=this.startDate.clone(),
c.hour(b),c.minute(d),c.second(e),this.setStartDate(c),this.singleDatePicker?this.endDate=this.startDate.clone():this.endDate&&this.endDate.format("YYYY-MM-DD")==c.format("YYYY-MM-DD")&&this.endDate.isBefore(c)&&this.setEndDate(c.clone())):this.endDate&&(c=this.endDate.clone(),c.hour(b),c.minute(d),c.second(e),this.setEndDate(c));this.updateCalendars();this.updateFormInputs();this.renderTimePicker("left");this.renderTimePicker("right")},elementChanged:function(){if(this.element.is("input")&&this.element.val().length){var b=
this.element.val().split(this.locale.separator),a=null,c=null;2===b.length&&(a=e(b[0],this.locale.format),c=e(b[1],this.locale.format));if(this.singleDatePicker||null===a||null===c)c=a=e(this.element.val(),this.locale.format);a.isValid()&&c.isValid()&&(this.setStartDate(a),this.setEndDate(c),this.updateView())}},keydown:function(b){9!==b.keyCode&&13!==b.keyCode||this.hide();27===b.keyCode&&(b.preventDefault(),b.stopPropagation(),this.hide())},updateElement:function(){if(this.element.is("input")&&
this.autoUpdateInput){var b=this.startDate.format(this.locale.format);this.singleDatePicker||(b+=this.locale.separator+this.endDate.format(this.locale.format));b!==this.element.val()&&this.element.val(b).trigger("change")}},remove:function(){this.container.remove();this.element.off(".daterangepicker");this.element.removeData()}};f.fn.daterangepicker=function(b,a){var c=f.extend(!0,{},f.fn.daterangepicker.defaultOptions,b);this.each(function(){var b=f(this);b.data("daterangepicker")&&b.data("daterangepicker").remove();
b.data("daterangepicker",new k(b,c,a))});return this};return k});
