var $jscomp={scope:{}};$jscomp.defineProperty="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(c.get||c.set)throw new TypeError("ES3 does not support getters and setters.");a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)};$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);$jscomp.SYMBOL_PREFIX="jscomp_symbol_";
$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};$jscomp.symbolCounter_=0;$jscomp.Symbol=function(a){return $jscomp.SYMBOL_PREFIX+(a||"")+$jscomp.symbolCounter_++};
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.iterator;a||(a=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("iterator"));"function"!=typeof Array.prototype[a]&&$jscomp.defineProperty(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.arrayIterator(this)}});$jscomp.initSymbolIterator=function(){}};$jscomp.arrayIterator=function(a){var b=0;return $jscomp.iteratorPrototype(function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}})};
$jscomp.iteratorPrototype=function(a){$jscomp.initSymbolIterator();a={next:a};a[$jscomp.global.Symbol.iterator]=function(){return this};return a};$jscomp.polyfill=function(a,b,c,d){if(b){c=$jscomp.global;a=a.split(".");for(d=0;d<a.length-1;d++){var e=a[d];e in c||(c[e]={});c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&$jscomp.defineProperty(c,a,{configurable:!0,writable:!0,value:b})}};
$jscomp.polyfill("Array.from",function(a){return a?a:function(a,c,d){$jscomp.initSymbolIterator();c=null!=c?c:function(a){return a};var b=[],f=a[Symbol.iterator];if("function"==typeof f)for(a=f.call(a);!(f=a.next()).done;)b.push(c.call(d,f.value));else for(var f=a.length,g=0;g<f;g++)b.push(c.call(d,a[g]));return b}},"es6-impl","es3");
function getSelectedText(){window.getSelection?txt=window.getSelection():window.document.getSelection?txt=window.document.getSelection():window.document.selection&&(txt=window.document.selection.createRange().text);return txt}function serialize(a){var b=[];a.querySelectorAll("[name]").forEach(function(a){b.push(a.name+"="+a.value)});return 0<b.length?b.join("&"):!1}
function quickview(a,b,c){document.getElementById("quickview-image"+a).src=b;document.querySelectorAll(".quickview-image-"+a+" img").forEach(function(a){a.classList.remove("active")});c.classList.add("active")}function trackAdClick(a){fetch("core/trackad.php",{method:"POST",headers:{"Content-type":"application/x-www-form-urlencoded; charset=UTF-8"},body:"id="+a})}
document.addEventListener("submit",function(a){if(a.target.closest(".auroraForm")){a.preventDefault();var b=a.target.closest(".auroraForm").getAttribute("data-formtype"),c=document.querySelector("#"+b+"-btn").innerHTML,d=a.target.closest(".auroraForm").getAttribute("action"),e=serialize(a.target.closest(".auroraForm"));if("testimonial"==b||"review"==b)e+="&rating="+document.querySelector('input[name="rating"]:checked').value;"booking"==b&&(e+="&rid="+document.querySelector('input[name="rid"]:checked').value);
document.querySelector("#"+b+"-btn").innerHTML='<i class="i i-spin"><svg role="img" focusable="false" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 14 14"><path d="m 4.62,11.2 q 0,0.525 -0.371875,0.8925 Q 3.87625,12.46 3.36,12.46 2.835,12.46 2.4675,12.0925 2.1,11.725 2.1,11.2 2.1,10.675 2.4675,10.3075 2.835,9.94 3.36,9.94 3.87625,9.94 4.248125,10.3075 4.62,10.675 4.62,11.2 z m 3.78,1.68 q 0,0.46375 -0.328125,0.791875 Q 7.74375,14 7.28,14 6.81625,14 6.488125,13.671875 6.16,13.34375 6.16,12.88 6.16,12.41625 6.488125,12.088125 6.81625,11.76 7.28,11.76 q 0.46375,0 0.791875,0.328125 Q 8.4,12.41625 8.4,12.88 z M 3.08,7.28 Q 3.08,7.8575 2.66875,8.26875 2.2575,8.68 1.68,8.68 1.1025,8.68 0.69125,8.26875 0.28,7.8575 0.28,7.28 0.28,6.7025 0.69125,6.29125 1.1025,5.88 1.68,5.88 2.2575,5.88 2.66875,6.29125 3.08,6.7025 3.08,7.28 z m 9.1,3.92 q 0,0.4025 -0.28875,0.69125 Q 11.6025,12.18 11.2,12.18 10.7975,12.18 10.50875,11.89125 10.22,11.6025 10.22,11.2 q 0,-0.4025 0.28875,-0.69125 Q 10.7975,10.22 11.2,10.22 q 0.4025,0 0.69125,0.28875 Q 12.18,10.7975 12.18,11.2 z M 4.9,3.36 Q 4.9,3.99875 4.449375,4.449375 3.99875,4.9 3.36,4.9 2.72125,4.9 2.270625,4.449375 1.82,3.99875 1.82,3.36 1.82,2.72125 2.270625,2.270625 2.72125,1.82 3.36,1.82 3.99875,1.82 4.449375,2.270625 4.9,2.72125 4.9,3.36 z M 8.96,1.68 q 0,0.7 -0.49,1.19 Q 7.98,3.36 7.28,3.36 6.58,3.36 6.09,2.87 5.6,2.38 5.6,1.68 5.6,0.98 6.09,0.49 6.58,0 7.28,0 7.98,0 8.47,0.49 8.96,0.98 8.96,1.68 z m 4.76,5.6 q 0,0.35 -0.245,0.595 Q 13.23,8.12 12.88,8.12 12.53,8.12 12.285,7.875 12.04,7.63 12.04,7.28 12.04,6.93 12.285,6.685 12.53,6.44 12.88,6.44 q 0.35,0 0.595,0.245 Q 13.72,6.93 13.72,7.28 z M 11.9,3.36 q 0,0.28875 -0.205625,0.494375 Q 11.48875,4.06 11.2,4.06 10.91125,4.06 10.705625,3.854375 10.5,3.64875 10.5,3.36 10.5,3.07125 10.705625,2.865625 10.91125,2.66 11.2,2.66 q 0.28875,0 0.494375,0.205625 Q 11.9,3.07125 11.9,3.36 z"/></svg></i>';
fetch(d,{method:a.target.closest(".auroraForm").getAttribute("method"),headers:{"Content-type":"application/x-www-form-urlencoded; charset=UTF-8"},body:e}).then(function(a){return a.text()}).then(function(a){console.log(a);a=a.split("|");var d=document.getElementById(a[0]),e=document.createElement(a[1]);e.className=a[3];e.innerHTML=a[4];null!=document.querySelector(".not")&&document.querySelector(".not").remove();"prepend"==a[2]?d.insertBefore(e,d.firstChild):"append"==a[2]?d.appendChild(e):"after"==
a[2]?d.after(e):"before"==a[2]?d.before(e):"replace"==a[2]&&(d.innerHTML="<"+a[1]+' class="'+a[3]+'">'+a[4]+"</"+a[1]+">");"replace"!=a[2]&&(document.querySelector("#"+b+"-btn").innerHTML=c)})}});
document.addEventListener("keyup",function(a){a.target.closest("#postcode")&&(a=document.getElementById("postcode").value,3<a.length&&fetch("http://api.jsacreative.com.au/v1/suburbs?postcode="+a,{method:"GET"}).then(function(a){if(a.ok)return a.json()}).then(function(a){if(""!=a){for(var b='<ul class="mx-3">',d=0;d<a.length;d++)b+='<li class="d-block pt-0"><a id="postcodeitem'+d+'" href="javascript:setAddress(`postcodeitem'+d+'`);" data-state="'+a[d].state.name+'" data-suburb="'+a[d].name+'">'+a[d].postcode+
", "+a[d].name+", "+a[d].state.name+"</a></li>";b+="</ul>";document.getElementById("postcodelist").innerHTML=b;document.querySelector("#postcodelist").classList.remove("d-none")}else document.querySelector("#postcodelist").classList.add("d-none"),document.getElementById("postcodelist").innerHTML=""}))});
function setAddress(a){document.querySelector("#state").value=document.querySelector("#"+a).getAttribute("data-state");document.querySelector("#suburb").value=document.querySelector("#"+a).getAttribute("data-suburb");document.querySelector("#postcodelist").classList.add("d-none");document.getElementById("postcodelist").innerHTML=""}
document.addEventListener("click",function(a){if(a.target.closest(".nolightbox")){a.preventDefault();var b=a.target.closest(".nolightbox").getAttribute("href"),c=a.target.closest(".nolightbox").getAttribute("data-caption");document.getElementById("figureimage").removeAttribute("srcset");document.getElementById("figureimage").src=b;document.getElementById("figcaption").innerHTML=c}if(a.target.closest(".qtyminus")){a.preventDefault();var d=a.target.getAttribute("data-id");a.target.getAttribute("data-qid");
var b=document.getElementById("qtyform"+d),c=document.getElementById("dqty"+d),d=document.getElementById("qty"+d),e=Number(d.value)||0,e=e-1;d.value=e;c.innerText=e;b.submit()}a.target.closest(".qtyplus")&&(a.preventDefault(),d=a.target.getAttribute("data-id"),a.target.getAttribute("data-qid"),b=document.getElementById("qtyform"+d),c=document.getElementById("dqty"+d),d=document.getElementById("qty"+d),e=Number(d.value)||0,e+=1,1>e&&(e=1),d.value=e,c.innerText=e,b.submit());a.target.closest(".banner-dismiss")&&
(a.preventDefault(),b=document.querySelector(".banner").getAttribute("data-banner"),document.querySelector("#banner").classList.add("slide-out-bottom"),localStorage.setItem("banner"+b+"Closed","true"));a.target.closest(".opener")&&a.target.parentElement.classList.toggle("open");a.target.closest(".auroraForm")&&(b=a.target.closest(".auroraForm").getAttribute("data-formtype"),document.querySelector("#"+b+"-btn").removeAttribute("disabled"));a.target.closest(".getquote")&&(c=a.target.getAttribute("data-postid"),
b=getSelectedText(),""==b&&(b=document.querySelector("#forum-post-"+c).innerHTML),c=document.querySelector("#forum-user-"+c).innerHTML,$("#da").summernote("pasteHTML","<blockquote><cite>"+c+" wrote:</cite>"+b+"</blockquote>"));if(a.target.closest(".addCart")){a=document.querySelectorAll('select[name="options[]"]');b="";if(0<a.length){for(c=0;c<a.length;c++)""!=a[c].value&&(b+=a[c].value+",");b=b.replace(/[, ]+$/,"").trim()}fetch("core/add_cart.php",{method:"POST",headers:{"Content-type":"application/x-www-form-urlencoded; charset=UTF-8"},
body:"id="+document.querySelector(".addCart").getAttribute("data-cartid")+"&opt="+b}).then(function(a){return a.json()}).then(function(a){if("nomore"==a)alert("Purchase Limit Reached!");else if("wholesaleoutside"==a)alert("Wholesale purchasing is restricted only to items in your account rank!");else{document.querySelector(".shoppingcart").innerHTML=a;var b=document.querySelector("#cartage"),c=document.querySelector("#sidecart");b.hasChildNodes()&&fetch("core/update_cartage.php").then(function(a){return a.text()}).then(function(a){c.classList.remove("d-none");
c.classList.remove("jello");c.classList.add("jello");b.innerHTML=a})}})}});
function addQuickCart(a){var b=document.querySelectorAll('select[name="options[]"]'),c="";if(0<b.length){for(var d=0;d<b.length;d++)""!=b[d].value&&(c+=b[d].value+",");c=c.replace(/[, ]+$/,"").trim()}fetch("core/add_cart.php",{method:"POST",headers:{"Content-type":"application/x-www-form-urlencoded; charset=UTF-8"},body:"id="+a+"&opt="+c}).then(function(a){return a.json()}).then(function(a){if("nomore"==a)alert("Purchase Limit Reached!");else if("wholesaleoutside"==a)alert("Wholesale purchasing is restricted only to items in your account rank!");
else{document.querySelector(".cart").innerHTML=a;var b=document.querySelector("#cartage"),c=document.querySelector("#sidecart");b.hasChildNodes()&&fetch("core/update_cartage.php").then(function(a){return a.text()}).then(function(a){c.classList.remove("d-none");c.classList.remove("jello");c.classList.add("jello");b.innerHTML=a})}})}
function selectOption(a,b){document.querySelector("#"+b+"options").value=a;document.querySelector(".optionslist"+b).classList.remove("optionselected");document.querySelector("#optionselected"+a).classList.add("optionselected")}
document.addEventListener("DOMContentLoaded",function(a){a=document.querySelectorAll(".youtube");for(var b=0;b<a.length;b++)if(!a[b].hasAttribute("data-fancybox")){var c="https://img.youtube.com/vi/"+a[b].dataset.embed+"/maxresdefault.jpg";a[b].setAttribute("itemprop","video");a[b].setAttribute("itemscope","");a[b].setAttribute("itemtype","http://schema.org/VideoObject");a[b].innerHTML='<meta itemprop="embedURL" content="https://www.youtube.com/embed/'+a[b].dataset.embed+'"><img style="cursor: pointer;" src="'+
c+'"><div class="play"></div>';a[b].addEventListener("click",function(){this.innerHTML='<iframe width="560" height="315" frameBorder="0" allow="accelerometer;autoplay;encrypted-media;gyroscope;picture-in-picture" src="https://www.youtube.com/embed/'+this.dataset.embed+'?enablejsapi=1&rel=0&showinfo=0&autoplay=1" allowFullScreen="allowfullscreen"></iframe>'})}});function clean0(a){10>a&&(a="0"+a);return a}
function checkboxNotify(){if(0==Array.from(document.querySelectorAll(".module-check")).reduce(function(a,c){return a||c.checked},!1)){var a=document.getElementById("module-notification");a.innerHTML="At least one option must be selected or completed!";a.classList.toggle("d-none");event.preventDefault();return!1}return!0}
function acceptShift(a,b){document.querySelector("#shift"+a).classList.remove("d-none");fetch("core/updateshift.php",{method:"POST",headers:{"Content-type":"application/x-www-form-urlencoded;charset=UTF-8"},body:"id="+a+"&uid="+b}).then(function(a){return a.text()}).then(function(b){"error"!=b?(document.querySelector("#shift"+a).classList.add("alert-success"),document.querySelector("#shift"+a).innerHTML=b):(document.querySelector("#shift"+a).classList.add("alert-danger"),""===b?document.querySelector("#shift"+
a).innerHTML="Error: "+b:document.querySelector("#shift"+a).innerHTML="There was an issue returning the output data!")})}
function updateChat(){chatTimer=null;fetch("core/chat.php",{method:"POST",headers:{"Content-type":"application/x-www-form-urlencoded;charset=UTF-8"},body:"sid="+document.querySelector("#chatsid").value}).then(function(a){return a.text()}).then(function(a){"none"!=a&&("|*|*|*|*|*|"!=a&&(document.querySelector("#chatScreen").innerHTML=a),""!=a&&document.querySelector("#chatBody").classList.remove("d-none"),document.querySelector("#chatScreen").scrollTop=9999999)});clearTimeout(chatTimer);chatTimer=
setTimeout(function(){updateChat()},2500)}
function initChat(){chatTimer=null;fetch("core/chat.php",{method:"POST",headers:{"Content-type":"application/x-www-form-urlencoded;charset=UTF-8"},body:"sid="+document.querySelector("#chatsid").value}).then(function(a){return a.text()}).then(function(a){"none"!=a&&("|*|*|*|*|*|"!=a&&(document.querySelector("#chatScreen").innerHTML=a),""!=a&&(document.querySelector("#chatBody").classList.remove("d-none"),document.querySelector(".chat-close").classList.toggle("d-none"),document.querySelector(".chat-open").classList.toggle("d-none")),
document.querySelector("#chatBody").classList.contains("d-none")||document.querySelectorAll(".chathideme,.chatunhideme").forEach(function(a){a.classList.toggle("d-none")}),clearTimeout(chatTimer));document.querySelector("#chatScreen").scrollTop=9999999})}
document.addEventListener("DOMContentLoaded",function(a){null!=document.getElementById("chatHeader")&&(document.getElementById("chatHeader").onclick=function(){document.querySelector("#chatBody").classList.toggle("d-none");document.querySelector(".chat-close").classList.toggle("d-none");document.querySelector(".chat-open").classList.toggle("d-none");document.getElementById("chatBody").classList.contains("d-none")&&clearTimeout(chatTimer)},document.getElementById("startChat").onclick=function(){var a=
document.querySelector("#chatName").value,c=document.querySelector("#chatEmail").value;document.querySelector("#chatNameError").classList.contains("d-none")||document.querySelector("#chatNameError").classList.add("d-none");document.querySelector("#chatEmailError").classList.contains("d-none")||document.querySelector("#chatEmailError").classList.add("d-none");""==a||""==c?(""==a&&document.querySelector("#chatNameError").classList.remove("d-none"),""==c&&document.querySelector("#chatEmailError").classList.remove("d-none")):
c.match(/^[^\s@]+@[^\s@]+\.[^\s@]+$/)?fetch("core/chat.php",{method:"POST",headers:{"Content-type":"application/x-www-form-urlencoded;charset=UTF-8"},body:"sid="+document.querySelector("#chatsid").value+"&who="+document.querySelector("#chatwho").value+"&name="+a+"&email="+document.querySelector("#chatEmail").value+"&message=|*|*|*|*|*|"}).then(function(a){return a.text()}).then(function(a){"available"==a&&"|*|*|*|*|*|"!=a?document.querySelector("#chatScreen").innerHTML='<ul><li class="admin"><p>Hello '+
document.querySelector("#chatName").value+", how can we assist you?</p></li></ul>":document.querySelector("#chatScreen").innerHTML='<ul><li class="admin"><p>Hello '+document.querySelector("#chatName").value+", there is currently no operators available to assist you, however, you can leave a message that will be stored, along with your email so an operator can contact when available.</p></li></ul>";document.querySelector("#chatScreen").scrollTop=9999999;document.querySelector("#chatMessage").value=
"";document.querySelectorAll(".chathideme,.chatunhideme").forEach(function(a){a.classList.toggle("d-none")});clearTimeout(chatTimer)}):document.querySelector("#chatEmailError").classList.remove("d-none")},document.getElementById("chatButton").onclick=function(){fetch("core/chat.php",{method:"POST",headers:{"Content-type":"application/x-www-form-urlencoded;charset=UTF-8"},body:"sid="+document.querySelector("#chatsid").value+"&who="+document.querySelector("#chatwho").value+"&name="+document.querySelector("#chatName").value+
"&email="+document.querySelector("#chatEmail").value+"&message="+document.querySelector("#chatMessage").value}).then(function(a){return a.text()}).then(function(a){"|*|*|*|*|*|"!=a&&(document.querySelector("#chatScreen").innerHTML=a);document.querySelector("#chatScreen").scrollTop=9999999;document.querySelector("#chatMessage").value="";clearTimeout(chatTimer);chatTimer=setTimeout(function(){updateChat()},2500)})},document.getElementById("chatMessage").onkeyup=function(a){13===a.keyCode&&(a.preventDefault(),
fetch("core/chat.php",{method:"POST",headers:{"Content-type":"application/x-www-form-urlencoded;charset=UTF-8"},body:"sid="+document.querySelector("#chatsid").value+"&who="+document.querySelector("#chatwho").value+"&name="+document.querySelector("#chatName").value+"&email="+document.querySelector("#chatEmail").value+"&message="+document.querySelector("#chatMessage").value}).then(function(a){return a.text()}).then(function(a){"|*|*|*|*|*|"!=a&&(document.querySelector("#chatScreen").innerHTML=a);document.querySelector("#chatScreen").scrollTop=
9999999;document.querySelector("#chatMessage").value="";clearTimeout(chatTimer);chatTimer=setTimeout(function(){updateChat()},2500)}))})});function showAdInfo(a){a=document.getElementById(a);a.style.display="none"===a.style.display?"block":"none"};
