<?php
require'TextStatistics/Maths.php';
require'TextStatistics/Pluralise.php';
require'TextStatistics/Resource.php';
require'TextStatistics/Syllables.php';
require'TextStatistics/Text.php';
require'TextStatistics/TextStatistics.php';
use DaveChild\TextStatistics as TS;
$textStatistics = new TS\TextStatistics;
$text = $_POST['t'];
$gunScore = $textStatistics->gunningFogScore($text);
$gunText = $gunScore.' - ';
$gunScore = round($gunScore);
if($gunScore == 0 || $gunScore == 1 || $gunScore == 2 || $gunScore == 3 || $gunScore == 4 || $gunScore == 5) $gunText .= '5th Grade and Lower.';
if($gunScore == 6) $gunText .= '6th Grade.';
if($gunScore == 7) $gunText .= '7th Grade.';
if($gunScore == 8) $gunText .= '8th Grade.';
if($gunScore == 9) $gunText .= 'High School Early Years.';
if($gunScore == 10) $gunText .= 'High School Middle Years.';
if($gunScore == 11 || $gunScore == 12) $gunText .= 'High School Senior.';
if($gunScore == 13 || $gunScore == 14 || $gunScore == 15) $gunText .= 'College Junior.';
if($gunScore == 16) $gunText .= 'College Senior.';
if($gunScore == 17 || $gunScore == 18 || $gunScore == 19 || $gunScore == 20) $gunText .= 'Post Graduate.';
if($gunScore > 20) $gunText .= 'Post Graduate Plus.';
print DaveChild\TextStatistics\Text::wordCount($text).','.DaveChild\TextStatistics\Text::sentenceCount($text).','.$gunText;
